name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.239.18.251 << 'EOF'
            cd /home/ec2-user/Ecommerce-CC
            sudo yum update -y
            sudo yum install -y git python3 -y
            rm -rf Ecommerce-CC
            git clone https://github.com/abellzs/Ecommerce-CC.git
            cd Ecommerce-CC
            sudo pkill -f app.py || true
            sudo nohup python3 app.py > output.log 2>&1 &
          EOF
